---
output: word_document
---


```{r, echo = F, message = F, warning = F}
#Purpose: this document is supposed to investigate the percent threshold and CO2 filtering process. 

# Import the figures
BASE <- "C:/Users/dorh012/Documents/hector-SA-npar"
path <- list.files(file.path(BASE, "lab_notebooks", "percent_threshold", "figs"), full.names = T) 

fig_list <- get(load(path))

```




```{r, echo = F, fig.height=8, fig.width=8}
fig_list$single_filter

# * Applied a single filter to the rcp 26 results but used various percent threshold cut offs (40 to 100 % by 10)
# * The percent criteia is written as a porportion in the legend 
# * land flux and the temp filter have about the same number of passing runs with the 60 % fall in crieteria
# * No observation filter has an observation that meets the 100% criteria 
# * Atm CO2 had teh second highest number of runs passing the with the 90% cirteria and has the most consistent number of passing runs with increasing criteia 

```



```{r, echo = F, fig.height=10, fig.width=10}
fig_list$paramter_space

# * Recall that a decrease in dot density means that certain paramter combinations have been removed 
#   where as a decrease in range tells us a bit about the paramter space. 
# * Look at Q10 the growth filter, with more slecetive threshold criteria on the growth and 
#   land fulx filter we start to see that the lower bound of the q10 paramter space is being limited
# * Now let's look at beta so the atm CO2 filter really narrows down the beta paramter space and 
#   the number of pass runs decreases from 699 to 255 with the increasing passing criteria but the paramter 
#   space stays relatvily stable 
# * Where as with the CO2 growth filter the number of passing runs drops form 1003 to 28 and the paramter space really narrows down. 
# * Then we have the land flux filter, where the number of passing rusn drops from 2814 to 934 and the paramter 
#   space narrows down dirasitically. BUt the landflux parameter space does not over lap with the atm CO2 or the CO2 growth filter. 
#   (this is consistent with the next figure)

```



```{r, echo = F, fig.height=8, fig.width=8}
fig_list$filter_combos

# * There are a few paramter combinations that pass through both the atm CO2 and atm growth filters
# * There are more paramter combinatoins that pass thorugh both the atm CO2 and temp filters 
# * Only 4 pass through atm CO2 and ladn flux, this makes sense considering the paramter space figure above where we noticed there was 
#   little to no overlap in the parameter space
```